spring:
  application:
    name: todolist
  profiles:
    default: release
  web:
    resources:
      add-mappings: false
      welcome-page: classpath:/static/index.html

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    jmx:
      exposure:
        include: health
